#t = (input('digite algo : '))
t = 'work em silence'
print(f'Está capitalizado?{t.istitle()')
print(f'o tipo primitivo é {(type(t))}')
print('é numerico',t.isnumeric())
print('é letra ',t.isalpha())
print('é letra ou numero: ',t.isalnum())
print('é decimal :',t.isdecimal())
print('é tudo maísculo: ',t.isupper())
print('é tudo minusculo: ',t.islower())
print('pode ser impresso: ',t.isprintable())
